### ISSUE TITLE
Documentation additions

### ISSUE THREAD

**Issue by hcs0** [chevah/geck#64]
**Bold** terms, outside of headings, are names of customized configuration
examples like user **john** or **mary**.
These also indicate items outside of SFTPPlus that are affected by the
configuration. For example, with a ``path`` set to `log/app.log`, a user
will see **log/app.log**, **log/app.log.1**, etc created.

*Italics* are terms and names used from third party services that interface
with SFTPPlus.
This is to indicate the the term used is outside of our software.

---------

And results from https://github.com/chevah/server/pull/1290/files PR

**Comment by adiroiban** [comment]
Do we need this?

I expect that each project will have its own documentation rules, so as long as we document the rules inside the documentation for each project we don't have to document it here.

-------

but we can start the Chevah or ProAtria blog in which we let other know about these details

-----

Let me know if this is confusing ? :)

**Comment by hcs0** [comment]
I don't know.  I think it's too much work to start going around changing typefaces to make things consistent.  But having some consistency makes things better to read.

For example to talk about FTP server commands, the command is being bolded like:
```
**APPE** Request an upload with appending to existing file.
```
Whereas I think that APPE should be on its own line since it's an example of a command.

-------

At the same time though, there are some parts that make things harder to read because it's being applied consistently.

For example, if you write a configuration text like:
```
``ssl_cipher_list = RC4-SHA``
```
Which gives it the blue background style, then it makes the text harder to read:

<img width="926" alt="screen shot 2017-10-24 at 1 15 06 pm" src="https://user-images.githubusercontent.com/5868781/31940164-7024c294-b8bd-11e7-976a-2c2e3233d787.png">

And if it's on its own line then it will be easier to read. 

-------

So I don't think we should change things for the sake of it... but having some consistency for the users overall makes the documentation better.

So I might look at what's being bolded / italicied to see if another rule should be applied to it (like the blue / grey / own line rule) or if it's better off being on its own adnotation like tip / warning etc.

**Comment by adiroiban** [comment]
I understand your concern and I think that is a valid.

You are suggesting to create a guide which might not be perfect, but will cause the minimum changes for current version.

But in order to check that pages are consistent with the new guide, I think that we need to check each page.

So if we are reading each page anyway why not make a better guide and do all the changes now :) ?

**Comment by hcs0** [comment]
I sort of did that at https://github.com/chevah/server/pull/1289
Where I had a guide written in the PR and was doing the changes while going through the configuration pages.

I don't really mind / care if there is a section in geck, or not, for typographical rules.

**Comment by adiroiban** [comment]
We can have a section in geck, which describes the convention used in Geck itself :)

**Comment by hcs0** [comment]
I'm making it generic in case something else comes up later for documentation and geck since I don't want to add this change now.

**Comment by hcs0** [comment]
Also I don't know if I want to do implement this change.. seems to be additional overhead for documentation writers to think about.  But I will leave the issue open for other comments
