### ISSUE TITLE
Agree on a style for documentation writing and apply it

### ISSUE THREAD

**Issue by hcs0** [chevah/geck#73]
This is not covered in geck but it should be covered for future reference.

The following are just proposals based on how we already write / review documentation.

Once we agree, create a ticket to check and apply for future reviews.

**Language:** American English (ie `e.g. using a Domain Controller or other centralized identity
management systems`)

**How units are written:** SI style (English version) or International System of Units
For example, if writing large numbers use the example at  https://en.wikipedia.org/wiki/Decimal_mark#Examples_of_use (decimals) ie `100 000`.

**Comment by adiroiban** [comment]
there is https://developers.google.com/style/ and I think that we should just make a reference to it.
no need to reinvent the wheel.
