### ISSUE TITLE
Docker about repo updated each time new release is out

### ISSUE THREAD

**Issue by hcs0** [chevah/geck#75]
https://github.com/proatria/sftpplus-docker

Add this in the release manager job/process

**Comment by adiroiban** [comment]
Why update?

The latest version was created to use the trial version... so no need to update as the info will alwasy be valid

**Comment by adiroiban** [comment]
I think that we can close this.

The current docker-repo can be used with any SFTPPlus version, including the trial.

The fact that it talks about 3.29.0, is in the context of an example. Feel free to update the readme to make it clear that it can be used with any version
