### ISSUE TITLE
Fix `paver` script; migrate it to brink.sh

### ISSUE THREAD

**Issue by danuker** [chevah/geck#80]
> @adiroiban : I noticed that `paver generate` no longer works, precisely because versions are not pinned (like in my previous CI pull request).

The paver.sh needs to be migrated to brink.sh (see chevah/server brink.sh and brink.conf)
Try to work with @dumol to understand how we bootstrap the python virtualenv using brink.sh

@dumol I am not sure where we have to documentation for brink.sh , so this can be a good opportunity to create the reference documentation.,

_Originally posted by @adiroiban in https://github.com/chevah/geck/issues/79#issuecomment-769772349_

**Comment by dumol** [comment]
`brink.sh` is self-documented, it has extensive inline comments. Let me know if something is not clear. Although for the virtualenv bootstrap, Adi would be the go-to resource… ;-]

It should be a drop-in replacement for `paver.sh`, but maybe leave a link to it after removing the old script if unsure. Like this:
```
ln -s brink.sh paver.sh
```

**Comment by adiroiban** [comment]
brink.sh is our virtual environment bootstrap tool .
